//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISFInvoiceApplication.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAUserAccount
    {
        public IAUserAccount()
        {
            this.IAInvoices = new HashSet<IAInvoice>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int WarningLimit { get; set; }
        public int ErrorLimit { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public int InvoiceTotal { get; set; }
    
        public virtual ICollection<IAInvoice> IAInvoices { get; set; }
    }
}
